version: "3.9"
services:
  postgres:
    image: postgres:13
    volumes:
      - ./migrations/create.sql:/docker-entrypoint-initdb.d/create.sql
    environment:
      POSTGRES_DB: "cinematheque"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
